name: himawari_api
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=1_gnu
  - aiobotocore=2.1.0=pyhd8ed1ab_0
  - aiohttp=3.8.1=py39h3811e60_0
  - aioitertools=0.10.0=pyhd8ed1ab_0
  - aiosignal=1.2.0=pyhd8ed1ab_0
  - async-timeout=4.0.2=pyhd8ed1ab_0
  - attrs=21.4.0=pyhd8ed1ab_0
  - blinker=1.4=py_1
  - bokeh=2.4.2=py39hf3d152e_0
  - botocore=1.23.24=pyhd8ed1ab_0
  - brotlipy=0.7.0=py39h3811e60_1003
  - bzip2=1.0.8=h7f98852_4
  - c-ares=1.18.1=h7f98852_0
  - ca-certificates=2021.10.8=ha878542_0
  - cachetools=5.0.0=pyhd8ed1ab_0
  - certifi=2021.10.8=py39hf3d152e_1
  - cffi=1.15.0=py39h4bc2ebd_0
  - charset-normalizer=2.0.12=pyhd8ed1ab_0
  - click=8.0.4=py39hf3d152e_0
  - cloudpickle=2.0.0=pyhd8ed1ab_0
  - colorama=0.4.4=pyh9f0ad1d_0
  - cryptography=36.0.0=py39h9ce1e76_0
  - cytoolz=0.11.2=py39h3811e60_1
  - dask=2022.3.0=pyhd8ed1ab_0
  - dask-core=2022.3.0=pyhd8ed1ab_0
  - decorator=5.1.1=pyhd8ed1ab_0
  - distributed=2022.3.0=pyhd8ed1ab_0
  - freetype=2.10.4=h0708190_1
  - frozenlist=1.3.0=py39h3811e60_0
  - fsspec=2022.2.0=pyhd8ed1ab_0
  - gcsfs=2022.2.0=pyhd8ed1ab_0
  - giflib=5.2.1=h36c2ea0_2
  - google-api-core=2.5.0=pyhd8ed1ab_0
  - google-auth=2.6.2=pyh6c4a22f_0
  - google-auth-oauthlib=0.5.1=pyhd8ed1ab_0
  - google-cloud-core=2.2.2=pyh6c4a22f_0
  - google-cloud-storage=2.1.0=pyh6c4a22f_0
  - google-crc32c=1.1.2=py39hb81f231_2
  - google-resumable-media=2.1.0=pyh6c4a22f_0
  - googleapis-common-protos=1.56.0=py39hf3d152e_0
  - grpcio=1.44.0=py39h336bf08_0
  - heapdict=1.0.1=py_0
  - idna=3.3=pyhd8ed1ab_0
  - jbig=2.1=h7f98852_2003
  - jinja2=3.0.3=pyhd8ed1ab_0
  - jmespath=0.10.0=pyh9f0ad1d_0
  - jpeg=9e=h7f98852_0
  - kerchunk=0.0.6=pyhd8ed1ab_0
  - lcms2=2.12=hddcbb42_0
  - ld_impl_linux-64=2.36.1=hea4e1c9_2
  - lerc=3.0=h9c3ff4c_0
  - libblas=3.9.0=13_linux64_openblas
  - libcblas=3.9.0=13_linux64_openblas
  - libcrc32c=1.1.2=h9c3ff4c_0
  - libdeflate=1.10=h7f98852_0
  - libffi=3.4.2=h7f98852_5
  - libgcc-ng=11.2.0=h1d223b6_14
  - libgfortran-ng=11.2.0=h69a702a_14
  - libgfortran5=11.2.0=h5c6108e_14
  - libgomp=11.2.0=h1d223b6_14
  - liblapack=3.9.0=13_linux64_openblas
  - libnsl=2.0.0=h7f98852_0
  - libopenblas=0.3.18=pthreads_h8fe5266_0
  - libpng=1.6.37=h21135ba_2
  - libprotobuf=3.19.4=h780b84a_0
  - libstdcxx-ng=11.2.0=he4da1e4_14
  - libtiff=4.3.0=h542a066_3
  - libuuid=2.32.1=h7f98852_1000
  - libwebp=1.2.2=h3452ae3_0
  - libwebp-base=1.2.2=h7f98852_1
  - libxcb=1.13=h7f98852_1004
  - libzlib=1.2.11=h36c2ea0_1013
  - locket=0.2.0=py_2
  - lz4-c=1.9.3=h9c3ff4c_1
  - markupsafe=2.1.1=py39hb9d737c_0
  - msgpack-python=1.0.3=py39h1a9c180_0
  - multidict=6.0.2=py39h3811e60_0
  - ncurses=6.3=h9c3ff4c_0
  - numpy=1.22.3=py39h18676bf_0
  - oauthlib=3.2.0=pyhd8ed1ab_0
  - openjpeg=2.4.0=hb52868f_1
  - openssl=3.0.0=h7f98852_2
  - packaging=21.3=pyhd8ed1ab_0
  - pandas=1.4.1=py39hde0f152_0
  - partd=1.2.0=pyhd8ed1ab_0
  - pillow=9.0.1=py39hae2aec6_2
  - pip=22.0.4=pyhd8ed1ab_0
  - protobuf=3.19.4=py39he80948d_0
  - psutil=5.9.0=py39h3811e60_0
  - pthread-stubs=0.4=h36c2ea0_1001
  - pyasn1=0.4.8=py_0
  - pyasn1-modules=0.2.7=py_0
  - pycparser=2.21=pyhd8ed1ab_0
  - pyjwt=2.3.0=pyhd8ed1ab_1
  - pyopenssl=22.0.0=pyhd8ed1ab_0
  - pyparsing=3.0.7=pyhd8ed1ab_0
  - pysocks=1.7.1=py39hf3d152e_4
  - python=3.9.10=hc74c709_2_cpython
  - python-dateutil=2.8.2=pyhd8ed1ab_0
  - python_abi=3.9=2_cp39
  - pytz=2022.1=pyhd8ed1ab_0
  - pyu2f=0.1.5=pyhd8ed1ab_0
  - pyyaml=6.0=py39h3811e60_3
  - readline=8.1=h46c0cb4_0
  - requests=2.27.1=pyhd8ed1ab_0
  - requests-oauthlib=1.3.1=pyhd8ed1ab_0
  - rsa=4.8=pyhd8ed1ab_0
  - s3fs=2022.2.0=pyhd8ed1ab_0
  - setuptools=60.10.0=py39hf3d152e_0
  - six=1.16.0=pyh6c4a22f_0
  - sortedcontainers=2.4.0=pyhd8ed1ab_0
  - sqlite=3.37.1=h4ff8645_0
  - tblib=1.7.0=pyhd8ed1ab_0
  - tk=8.6.12=h27826a3_0
  - toolz=0.11.2=pyhd8ed1ab_0
  - tornado=6.1=py39h3811e60_2
  - tqdm=4.63.0=pyhd8ed1ab_0
  - trollsift=0.4.0=pyhd8ed1ab_0
  - typing-extensions=4.1.1=hd8ed1ab_0
  - typing_extensions=4.1.1=pyha770c72_0
  - tzdata=2022a=h191b570_0
  - ujson=5.1.0=py39he80948d_0
  - urllib3=1.26.9=pyhd8ed1ab_0
  - wheel=0.37.1=pyhd8ed1ab_0
  - wrapt=1.14.0=py39hb9d737c_0
  - xorg-libxau=1.0.9=h7f98852_0
  - xorg-libxdmcp=1.1.3=h7f98852_0
  - xz=5.2.5=h516909a_1
  - yaml=0.2.5=h7f98852_2
  - yarl=1.7.2=py39h3811e60_1
  - zict=2.1.0=pyhd8ed1ab_0
  - zlib=1.2.11=h36c2ea0_1013
  - zstd=1.5.2=ha95c52a_0
prefix: /home/ghiggi/anaconda3/envs/goes_api
